import { useEffect, useMemo, useState } from "react";
import { CalendarCheck, Star } from "lucide-react";
import { api } from "../services/api";
import { validateAppointment } from "../utils/validation";

export default function BookDoctor({ user, setUser, setPage }) {
  const [doctors, setDoctors] = useState([]); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(""); const [spec, setSpec] = useState("All"); const [form, setForm] = useState({ dateTime: "", type: "Video Visit", reason: "" }); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(false);
  useEffect(()=>{ api.getDoctors().then(setDoctors); },[]);
  const filtered = useMemo(()=>doctors.filter(d => (spec==="All"||d.specialization===spec) && `${d.name} ${d.email} ${d.specialization}`.toLowerCase().includes(query.toLowerCase())),[doctors,query,spec]);
  async function book() { const nextErrors = validateAppointment(form); setErrors(nextErrors); if(Object.keys(nextErrors).length) return; setLoading(true); try { await api.bookDoctor({ patientId:user.id, doctorId:selected.id, ...form }); setUser({ ...user, doctorId: selected.id }); setPage("doctor"); } finally { setLoading(false); } }
  return <div><div className="page-title-block"><h2>Book a Doctor</h2><p>Search specialists, choose a time, and create a validated appointment request.</p></div><div className="toolbar"><input placeholder="Search by name, email, specialization..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={spec} onChange={e=>setSpec(e.target.value)}><option>All</option><option>Neurology</option><option>Sleep Medicine</option><option>Cardiology</option><option>Psychiatry</option><option>Biomedical Engineering</option></select></div><div className="doctor-grid">{filtered.map(d=><button className={`doctor-card ${selected?.id===d.id?"selected":""}`} key={d.id} onClick={()=>{setSelected(d); setForm(f=>({...f,dateTime:d.availability?.[0]||""}))}}><div className="avatar-xl">{d.avatar}</div><h3>{d.name}</h3><p>{d.specialization}</p><span>{d.email}</span><small><Star size={14}/> {d.rating || "New"} · License {d.license}</small></button>)}</div>{selected && <div className="booking-panel"><div><h3>Appointment Request</h3><p>{selected.name} · {selected.specialization}</p></div><div className="form-grid"><label>Visit type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Video Visit</option><option>In-person Follow-up</option><option>Sensor Review</option><option>Urgent Review</option></select></label><label>Available time<select value={form.dateTime} onChange={e=>setForm({...form,dateTime:e.target.value})}>{selected.availability.map(a=><option value={a} key={a}>{new Date(a).toLocaleString()}</option>)}</select>{errors.dateTime && <em>{errors.dateTime}</em>}</label><label className="full">Reason<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Describe symptoms, episode timing, or what you need reviewed..." />{errors.reason && <em>{errors.reason}</em>}</label></div><button className="primary-btn" onClick={book} disabled={loading}><CalendarCheck size={16}/>{loading?"Sending request...":"Send Appointment Request"}</button></div>}</div>
}
