import { useState } from "react";
import { Camera, Save } from "lucide-react";
import { api } from "../services/api";

export default function Profile({ user, setUser }) {
  const [form, setForm] = useState({ ...user }); const [saved, setSaved] = useState(false);
  const set = (k,v) => setForm(p=>({...p,[k]:v}));
  function file(e){ const f=e.target.files?.[0]; if(!f) return; const reader=new FileReader(); reader.onload=()=>set("photo",reader.result); reader.readAsDataURL(f); }
  async function save(){ const updated=await api.updateProfile(user, form); setUser(updated); setSaved(true); setTimeout(()=>setSaved(false),2200); }
  return <div><div className="profile-hero"><label className="profile-photo">{form.photo ? <img src={form.photo}/> : <span>{form.avatar || form.name?.slice(0,2)}</span>}<input type="file" accept="image/*" onChange={file}/><b><Camera size={14}/></b></label><div><p className="eyebrow">Profile & medical identity</p><h2>{form.name}</h2><p>{form.email}</p></div><button className="primary-btn" onClick={save}><Save size={16}/>Save Profile</button></div><div className="form-section"><h3>Personal Information</h3><div className="form-grid"><label>Full name<input value={form.name||""} onChange={e=>set("name",e.target.value)}/></label><label>Email<input value={form.email||""} onChange={e=>set("email",e.target.value)}/></label><label>Phone<input value={form.phone||""} onChange={e=>set("phone",e.target.value)}/></label><label>Bio<input value={form.bio||""} onChange={e=>set("bio",e.target.value)}/></label>{user.role==="Patient" && <><label>Age<input value={form.age||""} onChange={e=>set("age",e.target.value)}/></label><label>Date of birth<input type="date" value={form.dob||""} onChange={e=>set("dob",e.target.value)}/></label><label>Gender<select value={form.gender||""} onChange={e=>set("gender",e.target.value)}><option></option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></label><label>Marital status<select value={form.maritalStatus||""} onChange={e=>set("maritalStatus",e.target.value)}><option></option><option>Single</option><option>Married</option><option>Divorced</option><option>Widowed</option></select></label><label>Blood type<input value={form.bloodType||""} onChange={e=>set("bloodType",e.target.value)}/></label><label>Allergies<input value={form.allergies||""} onChange={e=>set("allergies",e.target.value)}/></label><label>Medications<input value={form.medications||""} onChange={e=>set("medications",e.target.value)}/></label><label>Emergency contact<input value={form.emergencyContact||""} onChange={e=>set("emergencyContact",e.target.value)}/></label><label className="full">Address<input value={form.address||""} onChange={e=>set("address",e.target.value)}/></label></>}{user.role==="Doctor" && <><label>Specialization<input value={form.specialization||""} onChange={e=>set("specialization",e.target.value)}/></label><label>License<input value={form.license||""} onChange={e=>set("license",e.target.value)}/></label></>}</div></div>{saved && <div className="toast">Profile updated.</div>}</div>
}
